CREATE TABLE USERS (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
    "NAME" VARCHAR(255), 
    EMAIL VARCHAR(50), 
    PASSWORD VARCHAR(20), 
    PHONE VARCHAR(50), 
    GENDER VARCHAR(50), 
    DOB VARCHAR(50), 
    PRIMARY KEY (ID));