CREATE TABLE DEVICE (
   ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 0,INCREMENT BY 1),
    "NAME" VARCHAR(255),
    "TYPE" VARCHAR(255),
    "PRICE" VARCHAR(255),
    "STOCK" VARCHAR(255),
    PRIMARY KEY (ID));
